[package]
name = "engine-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
memmap2.workspace = true
bytemuck.workspace = true
ndarray.workspace = true
half.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "matmul_bench"
harness = false
